# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desgin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 639)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(100000, 16777215))
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../imgs/conan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 361, 401))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QGroupBox(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 20, 381, 401))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.SelFile = QtWidgets.QPushButton(self.centralwidget)
        self.SelFile.setGeometry(QtCore.QRect(120, 430, 131, 51))
        self.SelFile.setObjectName("SelFile")
        self.RunProgram = QtWidgets.QPushButton(self.centralwidget)
        self.RunProgram.setGeometry(QtCore.QRect(360, 430, 131, 51))
        self.RunProgram.setObjectName("RunProgram")
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMinimumSize(QtCore.QSize(0, 160))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.BottomToolBarArea, self.toolBar)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setTitle(_translate("MainWindow", "        InPut"))
        self.label.setTitle(_translate("MainWindow", "          OutPut"))
        self.SelFile.setText(_translate("MainWindow", "SelFile"))
        self.RunProgram.setText(_translate("MainWindow", "RunProgram"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
